mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls")),
    path("company/", include("company.urls")),
    path("product/", include("product.urls")),
    path("team/", include("team.urls")),
    path("designation/", include("designation.urls")),
    path("ticket/", include("ticket.urls")),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/team/urls.py
from django.urls import path
from team import views

app_name = "team"
urlpatterns = [
    path("team-creation-page", views.teamCreationView, name = "team-creation"),
    path("team-updation-page/<int:team_id>", views.teamUpdationView, name = "team-updation"),
    path("team-deletion-page/<int:team_id>", views.teamDeletionView, name = "team-deletion"),
    path("", views.TeamListView.as_view(), name = "team-list"),
    path("<pk>/", views.TeamDetailView.as_view(), name= "team-details"),
]

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"
urlpatterns = [
    path("", views.index, name = "index"),
    path("sign-up/", views.UserCreationView, name = "sign-up"),
    path("logout/", views.logout, name = "logout"),
    path("change-password/", views.change_password, name = "change-password"),
    path("profile-view/", views.profile_view, name = "profile-view"),
    path("update-profile", views.update_profile, name = "update-profile"),
    path("dashboard/", views.dashboard, name = "dashboard"),
    path("add-user-in-company/<int:company_id>", views.companyUnassociatedUserProfile, name = "add-user-in-company"),
    path("assign-product-to-user/<int:product_id>", views.productUnassignedUserProfile, name = "assign-product-to-user"),
    path("assign-team-to-user/<int:team_id>", views.teamUnassignedUserProfile, name = "assign-team-to-user"),
    path("assign-designation-to-user/<int:designation_id>", views.designationUnassignedUserProfile, name = "assign-designation-to-user"),
    path("addCompanyToUserProfile/<str:username>/<int:company_id>", views.addCompanyToUserProfile, name = "add-company-to-user-profile"),
    path("addProductToUserProfile/<str:username>/<int:product_id>", views.addProductToUserProfile, name = "add-product-to-user-profile"),
    path("addTeamToUserProfile/<str:username>/<int:team_id>", views.addTeamToUserProfile, name = "add-team-to-user-profile"),
    path("addDesignationToUserProfile/<str:username>/<int:designation_id>", views.addDesignationToUserProfile, name = "add-designation-to-user-profile")
]

mysite/team/models.py
from django.db import models
from django.conf import settings
from product.models import Product
from django.utils import timezone

class Team(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField(max_length=500, default="Team Description")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null = True)
    administrator = models.ManyToManyField(settings.AUTH_USER_MODEL)
    created_on = models.DateTimeField(default=timezone.now, editable = False)

    def __str__(self):
        return self.name + " - " + self.product.name

mysite/team/forms.py
from django import forms
from team.models import Team
from django.forms import ModelForm
from product.models import Product
from django.contrib.auth import get_user_model
User = get_user_model()

class TeamCreationForm(ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
    
    def __init__(self, requested_user_id, *args, **kwargs):
        super(TeamCreationForm, self).__init__(*args, **kwargs)
        self.fields["product"].queryset = Product.objects.filter(administrator = requested_user_id)
        self.fields['administrator'].queryset = User.objects.filter(id = requested_user_id)

class TeamUpdationForm(ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
    
    def __init__(self, requested_user_id, team_id, *args, **kwargs):
        super(TeamUpdationForm, self).__init__(*args, **kwargs)
        administrator = Team.objects.get(id = team_id).administrator.all()
        non_administrator = User.objects.filter(team_assigned = team_id)
        self.fields["product"].queryset = Product.objects.filter(administrator = requested_user_id)
        self.fields["administrator"].queryset = administrator | non_administrator

mysite/team/views.py
from django.shortcuts import render, reverse
from team.forms import TeamCreationForm, TeamUpdationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from team.models import Team
from django.views import generic 
from django.contrib.auth.mixins import LoginRequiredMixin


@login_required
def teamCreationView(request):
    """
    This view handles the get and post request of Team Creation form.
    """
    if request.method == "POST":
        form = TeamCreationForm(request.user.id, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Team Added Successfully")
            return HttpResponseRedirect(reverse("user:dashboard"))
    else:
        context = {
            'form': TeamCreationForm(request.user.id),
        }
        return render(request,  "team/team-creation-page.html", context)

class TeamListView(LoginRequiredMixin, generic.ListView):
    """
    This view list the team objects associated with the user.
    """
    model = Team
    template_name = "team/index.html"

    def get_queryset(self):
        user_assigned_team = self.request.user.team_assigned.all()
        return Team.objects.filter(administrator = self.request.user.id).union(user_assigned_team)

class TeamDetailView(LoginRequiredMixin, generic.DetailView):
    """
    This view provides the details of Team object
    Requires pk for Team for querying the database.
    """
    model = Team
    template_name = "team/details.html"

@login_required
def teamUpdationView(request, team_id):
    """
    This view handles the get and post method of request for Team Updation Form.
    """
    requested_team = Team.objects.get(id = team_id)
    if request.user in requested_team.administrator.all():
        if request.method == "POST":
            form = TeamUpdationForm(request.user.id, team_id, request.POST, instance = requested_team)
            if request.user in requested_team.administrator.all():
                if form.is_valid():
                    form.save()
                    messages.success(request, "Team Details Updated Successfully")
                    return HttpResponseRedirect(reverse("user:dashboard"))
                else:
                    messages.error(request, "Please enter valid data")
                    return HttpResponseRedirect(reverse("user:dashboard"))
            else:
                messages.error(request, "You dont have permissions to update the company details")
                return HttpResponseRedirect(reverse("user:dashboard"))
        else:
            context = {
                'form': TeamUpdationForm(request.user.id,team_id, instance = requested_team),
            }
            return render(request,"team/team-updation-page.html", context)
    else:
        messages.error(request, "You are not eligible to update the team details")
        return HttpResponseRedirect(reverse("user:dashboard"))

@login_required
def teamDeletionView(request, team_id):
    """
    This view deletes the team object
    Requires pk of Team for deletion.
    """
    requested_team = Team.objects.get(id = team_id)
    if request.user in requested_team.administrator.all():
        requested_team.delete()
        messages.success(request, "Team deleted successfully")
        return HttpResponseRedirect(reverse("user:dashboard"))
    else:
        messages.error(request, "You are not eligible to delete the company details")
        return HttpResponseRedirect(reverse("user:dashboard"))

mysite/team/templates/team/details.html
{% extends 'mysite/base.html' %}
{% block section %}
<div class = "dashboard-container">
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-4 image-container">
     {% if object.product.logo %}
        <img src = {{ object.product.logo.url }} height = 150, width = 150> <br>
    {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-body">

 <h5 class="card-title">{{ object.name }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ object.product }}</h6>
    <p class="card-text">
    Team Description: {{ object.description }} <br>
    Created On: {{ object.created_on }} <br>
    Administrator: 
    {% for admin in object.administrator.all %}
        {{ admin }}
    {% endfor %}
    </p>
     {% if user in object.administrator.all %}
     <div class="button-container">
     <button class = "btn btn-primary"><a href = {% url "team:team-updation" object.id %}>Update Details </a></button>
        <button class = "btn btn-danger"><a href = {% url "team:team-deletion" object.id %}>Delete Team </a></button>
        <button class = "btn btn-success"><a href = {% url "user:assign-team-to-user" object.id %}>Add User</a></button>
         
         
         </div>
    {% endif %}
      </div>
    </div>
  </div>
</div>
</div>

{% endblock section %}

mysite/team/templates/team/index.html
{% extends 'mysite/base.html' %}
{% block section %}
<div class ="col-12 list-container">
{% if team_list %}
<ul>
    {% for team in team_list %}
       <li> <a href = {% url "team:team-details" team.id %}>{{team}}</a> </li>
    {% endfor %}
{% elif user.team_assigned %}
   <li> {{ user.team_assigned }}</li>
{% else %}
    You are not assigned in any team.
    </ul>
{% endif %}
</div>
<div class = "col-12 button-container">
<button type="button" class="btn btn-success"><a href = {% url "team:team-creation" %}>Add Team </a></button>
</div>
 
{% endblock %}

mysite/team/templates/team/team-creation-page.html
{% extends 'mysite/base.html' %}
{% block section %}
<div class="form-container">
<form action = "" method = "POST">
{% csrf_token %}
<div class="form-group row">
    {{ form.name.errors }}
    <label for="{{ form.name.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Name</label>
    {{ form.name }}
</div>

<div class="form-group row">
    {{ form.description.errors }}
    <label for="{{ form.description.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Description</label>
    {{ form.description }}
</div>

<div class="form-group row">
    {{ form.product.errors }}
    <label for="{{ form.product.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Product</label>
    {{ form.product }}
</div>

<div class="form-group row">
    {{ form.administrator.errors }}
    <label for="{{ form.administrator.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Administrator</label>
    {{ form.administrator }}
</div>
<button type = "submit" value = "Submit" class = "btn btn-success">Create New Team</button>
</form>
</div>
{% endblock %}

mysite/team/templates/team/team-updation-page.html
{% extends 'mysite/base.html' %}
{% block section %}
<div class="form-container">
<form action = "" method = "POST">
{% csrf_token %}
<div class="form-group row">
    {{ form.name.errors }}
    <label for="{{ form.name.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Name</label>
    {{ form.name }}
</div>

<div class="form-group row">
    {{ form.description.errors }}
    <label for="{{ form.description.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Description</label>
    {{ form.description }}
</div>

<div class="form-group row">
    {{ form.product.errors }}
    <label for="{{ form.product.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Product</label>
    {{ form.product }}
</div>

<div class="form-group row">
    {{ form.administrator.errors }}
    <label for="{{ form.administrator.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Administrator</label>
    {{ form.administrator }}
</div>
<button type = "submit" value = "Submit" class = "btn btn-success">Apply Changes</button>
</form>
</div>
{% endblock %}