mysite/company/urls.py
from django.urls import path
from company import views

app_name = "company"
urlpatterns = [
    path("company-creation-page", views.companyCreationView, name = "company-creation"),
    path("company-updation-page/<int:company_id>", views.companyUpdationView, name = "company-updation"),
    path("company-deletion-page/<int:company_id>", views.companyDeletionView, name = "company-deletion"),
    path("", views.CompanyListView.as_view(), name = "company-list"),
    path("<pk>/", views.CompanyDetailView.as_view(), name= "company-details"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls")),
    path("company/", include("company.urls")),
    path("product/", include("product.urls")),
    path("team/", include("team.urls")),
    path("designation/", include("designation.urls")),
    path("ticket/", include("ticket.urls")),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/product/urls.py
from django.urls import path
from product import views

app_name = "product"
urlpatterns = [
    path("product-creation-page", views.productCreationView, name = "product-creation"),
    path("product-updation-page/<int:product_id>", views.productUpdationView, name = "product-updation"),
    path("product-deletion-page/<int:product_id>", views.productDeletionView, name = "product-deletion"),
    path("", views.ProductListView.as_view(), name = "product-list"),
    path("<pk>/", views.ProductDetailView.as_view(), name= "product-details"),
]

mysite/team/urls.py
from django.urls import path
from team import views

app_name = "team"
urlpatterns = [
    path("team-creation-page", views.teamCreationView, name = "team-creation"),
    path("team-updation-page/<int:team_id>", views.teamUpdationView, name = "team-updation"),
    path("team-deletion-page/<int:team_id>", views.teamDeletionView, name = "team-deletion"),
    path("", views.TeamListView.as_view(), name = "team-list"),
    path("<pk>/", views.TeamDetailView.as_view(), name= "team-details"),
]

mysite/ticket/urls.py
from django.urls import path
from ticket import views


app_name = "ticket"
urlpatterns = [
    path("report-bug/", views.report_bug, name = "report-bug"),
    path("submitted-tickets/", views.SubmittedTicketsListView.as_view(), name = "submitted-tickets"),
    path("submitted-ticket-details/<int:pk>", views.SubmittedTicketDetailView.as_view(), name= "submitted-ticket-details"),
    path("review-tickets/", views.reviewTickets, name = "review-tickets"),
    path("ticket-details/<int:pk>", views.TicketDetailView.as_view(), name= "ticket-details"),
    path("ticket-updation/<int:ticket_id>", views.ticketUpdation, name = "update-ticket"),
    path("assigned-tickets/", views.AssignedTicketsListView.as_view(), name = "assigned-tickets"),
    path("ticket-dashboard/<int:pk>", views.AssignedTicketDashboardDetailView.as_view(), name = "ticket-dashboard"),
]

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"
urlpatterns = [
    path("", views.index, name = "index"),
    path("sign-up/", views.UserCreationView, name = "sign-up"),
    path("logout/", views.logout, name = "logout"),
    path("change-password/", views.change_password, name = "change-password"),
    path("profile-view/", views.profile_view, name = "profile-view"),
    path("update-profile", views.update_profile, name = "update-profile"),
    path("dashboard/", views.dashboard, name = "dashboard"),
    path("add-user-in-company/<int:company_id>", views.companyUnassociatedUserProfile, name = "add-user-in-company"),
    path("assign-product-to-user/<int:product_id>", views.productUnassignedUserProfile, name = "assign-product-to-user"),
    path("assign-team-to-user/<int:team_id>", views.teamUnassignedUserProfile, name = "assign-team-to-user"),
    path("assign-designation-to-user/<int:designation_id>", views.designationUnassignedUserProfile, name = "assign-designation-to-user"),
    path("addCompanyToUserProfile/<str:username>/<int:company_id>", views.addCompanyToUserProfile, name = "add-company-to-user-profile"),
    path("addProductToUserProfile/<str:username>/<int:product_id>", views.addProductToUserProfile, name = "add-product-to-user-profile"),
    path("addTeamToUserProfile/<str:username>/<int:team_id>", views.addTeamToUserProfile, name = "add-team-to-user-profile"),
    path("addDesignationToUserProfile/<str:username>/<int:designation_id>", views.addDesignationToUserProfile, name = "add-designation-to-user-profile")
]

mysite/templates/mysite/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Project</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome-free-5.14.0-web/css/all.min.css' %}" rel="stylesheet">

</head>

<body>
                            <!-- Navigation Starts Here-->
    <nav class="navbar navbar-expand-md">
        <a class="navbar-brand" href="{% url "user:index" %}"><span><i class="fas fa-bug"></i></span> Bug Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><i class="fas fa-arrow-down" style="color: #ffffff;"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "user:dashboard" %}"><span><i class="fas fa-columns"></i></span> Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "ticket:report-bug" %}"><span><i class="fas fa-exclamation-circle"></i></span> Report Bug</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "user:sign-up" %}"><span><i class="fa fa-user-plus"></i></span> Sign up</a>
                </li>
            {% endif %}
            </ul>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span><i class="fas fa-user"></i></span> {{ request.user.username }}
                      </a>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url "user:profile-view" %}">My Profile</a>
                        <a class="dropdown-item" href="{% url "user:change-password" %}">Change Password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url "user:logout" %}">Logout</a>
                      </div>
                </li>
            </ul>
            {% endif %}
        </div>
    </nav>
                        <!-- Navigation Ends Here -->
                            <!--Message Starts Here -->
     {% if messages %}
{% for message in messages %}
    <div class="message">
    <p {% if message.tags %} class = "{{ message.tags }}" {% endif %}> Hey {{ user.first_name }} {{ user.last_name }} ! {{ message }}</p></div>
    {% endfor %}
{% endif %}
                         <!-- Message Ends Here -->
  <section id="main">
        <div class="container-fluid">
            <div class="row">
             {% if request.user.is_authenticated %}
                <div class="col-12 col-md-4 col-lg-2">
                    <!--------------------------------------- Sidebar Starts Here -------------------------------------->
<div class="list-group sidebar mt-3">
    <a href={% url 'company:company-list'%} class="list-group-item list-group-item-action">
                            <span class="icon"><i class="fas fa-layer-group"></i></span> Company</a>
      <a href={% url 'product:product-list'%} class="list-group-item list-group-item-action"><span class="icon">
          <i class="fab fa-microsoft"></i></span> Products</a>
<a href={% url 'team:team-list'%} class="list-group-item list-group-item-action">
                            <span class="icon"><i class="fas fa-users"></i></span> Team </a>
 <a href={% url 'designation:designation-list'%} class="list-group-item list-group-item-action">
                            <span class="icon"><i class="fas fa-user-md"></i></span> Designation </a>
                            <a href={% url 'ticket:report-bug'%} class="list-group-item list-group-item-action">
                            <span class="icon"><i class="fas fa-exclamation-circle"></i></span> Report Bug </a>
                            <a href={% url 'ticket:submitted-tickets'%} class="list-group-item list-group-item-action">
                            <span class="icon"><i class="fas fa-envelope-open-text"></i></span> Submitted Tickets </a>
                            {% if True in user.administratorStatus.values %}
<a href={% url 'ticket:review-tickets'%} class="list-group-item list-group-item-action">
                            <span class="icon"><i class="fas fa-history"></i></span> Review Tickets </a>
                            <a href={% url 'ticket:assigned-tickets'%} class="list-group-item list-group-item-action">
                            <span class="icon"><i class="fas fa-hand-point-right"></i></span> Assigned Tickets </a>    
                            {% endif %}
</div>

                    <!--------------------------------------- Sidebar Ends Here ---------------------------------------->
                </div>
                {% endif %}
                <div class="col-12 col-md-8 col-lg-10 mt-3">
                    <section>
                {% block section %} {% endblock %}
                    </section>
                </div>
            </div>
        </div>
    </section>




   <script src="{% static 'jquery/jquery.slim.min.js' %}">
    </script>
    <script src="{% static 'popperjs/popper.min.js' %}">
    </script>
    <script src="{% static 'js/bootstrap.min.js' %}">
    </script>
</body>
</html>