mysite/designation/urls.py
from django.urls import path
from designation import views

app_name = "designation"
urlpatterns = [
    path("designation-creation-page", views.designationCreationView, name = "designation-creation"),
    path("designation-updation-page/<int:designation_id>", views.designationUpdationView, name = "designation-updation"),
    path("designation-deletion-page/<int:designation_id>", views.designationDeletionView, name = "designation-deletion"),
    path("", views.DesignationListView.as_view(), name = "designation-list"),
    path("<pk>/", views.DesignationDetailView.as_view(), name= "designation-details"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user.urls")),
    path("company/", include("company.urls")),
    path("product/", include("product.urls")),
    path("team/", include("team.urls")),
    path("designation/", include("designation.urls")),
    path("ticket/", include("ticket.urls")),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/team/urls.py
from django.urls import path
from team import views

app_name = "team"
urlpatterns = [
    path("team-creation-page", views.teamCreationView, name = "team-creation"),
    path("team-updation-page/<int:team_id>", views.teamUpdationView, name = "team-updation"),
    path("team-deletion-page/<int:team_id>", views.teamDeletionView, name = "team-deletion"),
    path("", views.TeamListView.as_view(), name = "team-list"),
    path("<pk>/", views.TeamDetailView.as_view(), name= "team-details"),
]

mysite/user/urls.py
from django.urls import path
from user import views

app_name = "user"
urlpatterns = [
    path("", views.index, name = "index"),
    path("sign-up/", views.UserCreationView, name = "sign-up"),
    path("logout/", views.logout, name = "logout"),
    path("change-password/", views.change_password, name = "change-password"),
    path("profile-view/", views.profile_view, name = "profile-view"),
    path("update-profile", views.update_profile, name = "update-profile"),
    path("dashboard/", views.dashboard, name = "dashboard"),
    path("add-user-in-company/<int:company_id>", views.companyUnassociatedUserProfile, name = "add-user-in-company"),
    path("assign-product-to-user/<int:product_id>", views.productUnassignedUserProfile, name = "assign-product-to-user"),
    path("assign-team-to-user/<int:team_id>", views.teamUnassignedUserProfile, name = "assign-team-to-user"),
    path("assign-designation-to-user/<int:designation_id>", views.designationUnassignedUserProfile, name = "assign-designation-to-user"),
    path("addCompanyToUserProfile/<str:username>/<int:company_id>", views.addCompanyToUserProfile, name = "add-company-to-user-profile"),
    path("addProductToUserProfile/<str:username>/<int:product_id>", views.addProductToUserProfile, name = "add-product-to-user-profile"),
    path("addTeamToUserProfile/<str:username>/<int:team_id>", views.addTeamToUserProfile, name = "add-team-to-user-profile"),
    path("addDesignationToUserProfile/<str:username>/<int:designation_id>", views.addDesignationToUserProfile, name = "add-designation-to-user-profile")
]

mysite/designation/models.py
from django.db import models
from django.conf import settings
from team.models import Team
from django.utils import timezone
class Designation(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField(max_length=500, default="Designation Description")
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null = True)
    administrator = models.ManyToManyField(settings.AUTH_USER_MODEL)
    created_on = models.DateTimeField(default=timezone.now, editable = False)

    def __str__(self):
        return self.name + " - " + self.team.name

mysite/designation/forms.py
from django import forms
from designation.models import Designation
from django.forms import ModelForm
from team.models import Team
from django.contrib.auth import get_user_model
User = get_user_model()

class DesignationCreationForm(ModelForm):
    class Meta:
        model = Designation
        fields = "__all__"
    
    def __init__(self, requested_user_id, *args, **kwargs):
        super(DesignationCreationForm, self).__init__(*args, **kwargs)
        self.fields["team"].queryset = Team.objects.filter(administrator = requested_user_id)
        self.fields['administrator'].queryset = User.objects.filter(id = requested_user_id)

class DesignationUpdationForm(ModelForm):
    class Meta:
        model = Designation
        fields = "__all__"
    
    def __init__(self, requested_user_id, designation_id, *args, **kwargs):
        super(DesignationUpdationForm, self).__init__(*args, **kwargs)
        administrator = Designation.objects.get(id = designation_id).administrator.all()
        non_administrator = User.objects.filter(designation_assigned = designation_id)
        self.fields["team"].queryset = Team.objects.filter(administrator = requested_user_id)
        self.fields["administrator"].queryset = administrator | non_administrator

mysite/designation/views.py
from django.shortcuts import render, reverse
from designation.forms import DesignationCreationForm, DesignationUpdationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import generic 
from django.contrib.auth.mixins import LoginRequiredMixin
from designation.models import Designation

@login_required
def designationCreationView(request):
    """
    This view handles the get and post method of request for Designation Creation Form
    """
    if request.method == "POST":
        form = DesignationCreationForm(request.user.id, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "New Designation Added Successfully")
            return HttpResponseRedirect(reverse("user:dashboard"))
    else:
        context = {
            'form': DesignationCreationForm(request.user.id),
        }
        return render(request,  "designation/designation-creation-page.html", context)

class DesignationListView(LoginRequiredMixin, generic.ListView):
    """
    This view lists all the designations of the requested user.
    """
    model = Designation
    template_name = "designation/index.html"

    def get_queryset(self):
        user_assigned_designation = self.request.user.designation_assigned.all()
        return Designation.objects.filter(administrator = self.request.user.id).union(user_assigned_designation)

class DesignationDetailView(LoginRequiredMixin, generic.DetailView):
    """
    This view displays the details of the designation object reqested by the user
    Requires the pk of Designation Object.
    """
    model = Designation
    template_name = "designation/details.html"

@login_required
def designationUpdationView(request, designation_id):
    """
    This view handles the get and post method request of designation updation form.
    """
    requested_designation = Designation.objects.get(id = designation_id)
    if request.user in requested_designation.administrator.all():
        if request.method == "POST":
            form = DesignationUpdationForm(request.user.id, designation_id, request.POST, instance = requested_designation)
            if request.user in requested_designation.administrator.all():
                if form.is_valid():
                    form.save()
                    messages.success(request, "Designation Details Updated Successfully")
                    return HttpResponseRedirect(reverse("user:dashboard"))
                else:
                    messages.error(request, "Please enter valid data")
                    return HttpResponseRedirect(reverse("user:dashboard"))
            else:
                messages.error(request, "You dont have permissions to update the company details")
                return HttpResponseRedirect(reverse("user:dashboard"))
        else:
            context = {
                'form': DesignationUpdationForm(request.user.id,designation_id, instance = requested_designation),
            }
            return render(request,"designation/designation-updation-page.html", context)
    else:
        messages.error(request, "You are not eligible to update the designation details")
        return HttpResponseRedirect(reverse("user:dashboard"))

@login_required
def designationDeletionView(request, designation_id):
    """
    This view deletes the designation object requested by the user through designation_id
    """
    requested_designation = Designation.objects.get(id = designation_id)
    if request.user in requested_designation.administrator.all():
        requested_designation.delete()
        messages.success(request, "Designation deleted successfully")
        return HttpResponseRedirect(reverse("user:dashboard"))
    else:
        messages.error(request, "You are not eligible to delete the company details")
        return HttpResponseRedirect(reverse("user:dashboard"))

mysite/designation/templates/designation/designation-creation-page.html
{% extends 'mysite/base.html' %}
{% block section %}
<div class="form-container">
<form action = "" method = "POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="form-group row">
    {{ form.name.errors }}
    <label for="{{ form.name.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Name</label>
    {{ form.name }}
</div>

<div class="form-group row">
    {{ form.description.errors }}
    <label for="{{ form.description.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Description</label>
    {{ form.description }}
</div>

<div class="form-group row">
    {{ form.team.errors }}
    <label for="{{ form.team.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Team</label>
    {{ form.team }}
</div>

<div class="form-group row">
    {{ form.administrator.errors }}
    <label for="{{ form.administrator.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Administrator</label>
    {{ form.administrator }}
</div>

<button type = "submit" value = "Submit" class = "btn btn-success">Create New Designation</button>
</form>
</div>
{% endblock %}

mysite/designation/templates/designation/designation-updation-page.html
{% extends 'mysite/base.html' %}
{% block section %}
<div class="form-container">
<form action = "" method = "POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="form-group row">
    {{ form.name.errors }}
    <label for="{{ form.name.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Name</label>
    {{ form.name }}
</div>

<div class="form-group row">
    {{ form.description.errors }}
    <label for="{{ form.description.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Description</label>
    {{ form.description }}
</div>

<div class="form-group row">
    {{ form.team.errors }}
    <label for="{{ form.team.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Team</label>
    {{ form.team }}
</div>

<div class="form-group row">
    {{ form.administrator.errors }}
    <label for="{{ form.administrator.id_for_label }}" class="col-sm-6 col-md-4 col-lg-2 col-form-label">Administrator</label>
    {{ form.administrator }}
</div>

<button type = "submit" value = "Submit" class = "btn btn-success">Apply Changes</button>
</form>
</div>
{% endblock %}

mysite/designation/templates/designation/details.html
{% extends 'mysite/base.html' %}
{% block section %}


<div class = "dashboard-container">
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-4 image-container">
     {% if object.product.logo %}
        <img src = {{ object.product.logo.url }} height = 150, width = 150> <br>
    {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-body">

 <h5 class="card-title">{{ object.name }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ object.team }}</h6>
    <p class="card-text">
    About Your Role: {{ object.description }} <br>
    Created On: {{ object.created_on }} <br>
    Administrator:
    {% for admin in object.administrator.all %}
        {{ admin }}
    {% endfor %}
    </p>
     {% if user in object.administrator.all %}
     <div class="button-container">
     <button class = "btn btn-primary"><a href = {% url "designation:designation-updation" object.id %}>Update Details </a></button>
        <button class = "btn btn-danger"><a href = {% url "designation:designation-deletion" object.id %}>Delete Designation </a></button>
        <button class = "btn btn-success"><a href = {% url "user:assign-designation-to-user" object.id %}>Add User</a></button>
         </div>
    {% endif %}
      </div>
    </div>
  </div>
</div>
</div>
{% endblock section %}

mysite/designation/templates/designation/index.html
{% extends 'mysite/base.html' %}
{% block section %}
<div class ="col-12 list-container">
{% if designation_list %}
<ul>
    {% for designation in designation_list %}
        <li><a href = {% url "designation:designation-details" designation.id %}>{{designation}}</a> </li>
    {% endfor %}
{% elif user.designation_assigned %}
    <li>{{ user.designation_assigned }} </li>
{% else %}
    You are not assigned in any designation.
    </ul>
{% endif %}
</div>
<div class = "col-12 button-container">
<button type="button" class="btn btn-success"><a href = {% url "designation:designation-creation" %}>Add Designation</a></button>
</div>
  
{% endblock %}